version: 2.1

orbs:
  node: circleci/node@5.0
  php: circleci/php@1.1

jobs:
  lint-js:
    docker:
      - image: cimg/node:14.19
    steps:
      - run: npm ci && npm run lint:js
  test-js:
    docker:
      - image: cimg/node:14.19
    steps:
      - run: npm ci && npm run test:js
  test-php:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - node/install-packages
      - php/install-packages
      - run: npm run build
      - run: composer test

workflows:
  build:
    jobs:
      - lint-js
      - test-js
      - test-php
