version: 2.1

orbs:
  node: circleci/node@5.0
  php: circleci/php@1.1

workflows:
  build:
    jobs:
      - node/run:
          npm-run: lint:js
      - node/run:
          npm-run: test:js
      - php/test
